# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'erp_tela.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
## ------Importando telas sistema---------###
from cliente_tela import Ui_form_cliente

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(548, 243)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lb_logoEmpresa = QtWidgets.QLabel(self.centralwidget)
        self.lb_logoEmpresa.setGeometry(QtCore.QRect(180, 140, 161, 51))
        self.lb_logoEmpresa.setStyleSheet("image:url(:/logoEmpresa/icons/logo_empresa.png)")
        self.lb_logoEmpresa.setText("")
        self.lb_logoEmpresa.setObjectName("lb_logoEmpresa")
        self.btn_cliente = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cliente.setGeometry(QtCore.QRect(0, 0, 61, 61))
        self.btn_cliente.setStyleSheet("image: url(:/icon_cliente/icons/cliente.png);\n"
"background-color: qradialgradient(spread:pad,cx:0.5,cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop: 0 rgba(255,255,255,0));")
        self.btn_cliente.setText("")
        self.btn_cliente.setObjectName("btn_cliente")
        self.btn_produtos = QtWidgets.QPushButton(self.centralwidget)
        self.btn_produtos.setGeometry(QtCore.QRect(120, 0, 61, 61))
        self.btn_produtos.setStyleSheet("image: url(:/icon_produtos/icons/produtos.png);\n"
"background-color: qradialgradient(spread:pad,cx:0.5,cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop: 0 rgba(255,255,255,0));")
        self.btn_produtos.setText("")
        self.btn_produtos.setObjectName("btn_produtos")
        self.btn_fornecedor = QtWidgets.QPushButton(self.centralwidget)
        self.btn_fornecedor.setGeometry(QtCore.QRect(60, 0, 61, 61))
        self.btn_fornecedor.setStyleSheet("\n"
"background-color: qradialgradient(spread:pad,cx:0.5,cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop: 0 rgba(255,255,255,0));\n"
"image: url(:/icon_fornecedor/icons/fornecedor.png);")
        self.btn_fornecedor.setText("")
        self.btn_fornecedor.setObjectName("btn_fornecedor")
        self.btn_vendas = QtWidgets.QPushButton(self.centralwidget)
        self.btn_vendas.setGeometry(QtCore.QRect(180, 0, 61, 61))
        self.btn_vendas.setStyleSheet("background-color: qradialgradient(spread:pad,cx:0.5,cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop: 0 rgba(255,255,255,0));\n"
"image: url(:/icon_vendas/icons/venda.png);")
        self.btn_vendas.setText("")
        self.btn_vendas.setObjectName("btn_vendas")
        self.btn_pagar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pagar.setGeometry(QtCore.QRect(240, 0, 61, 61))
        self.btn_pagar.setStyleSheet("image: url(:/icon_pagar/icons/contasPagar.png);\n"
"background-color: qradialgradient(spread:pad,cx:0.5,cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop: 0 rgba(255,255,255,0));")
        self.btn_pagar.setText("")
        self.btn_pagar.setObjectName("btn_pagar")
        self.btn_bancos = QtWidgets.QPushButton(self.centralwidget)
        self.btn_bancos.setGeometry(QtCore.QRect(300, 0, 61, 61))
        self.btn_bancos.setStyleSheet("image: url(:/icon_bancos/icons/banco.png);\n"
"background-color: qradialgradient(spread:pad,cx:0.5,cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop: 0 rgba(255,255,255,0));")
        self.btn_bancos.setText("")
        self.btn_bancos.setObjectName("btn_bancos")
        self.btn_receber = QtWidgets.QPushButton(self.centralwidget)
        self.btn_receber.setGeometry(QtCore.QRect(360, 0, 61, 61))
        self.btn_receber.setStyleSheet("image: url(:/icon_receber/icons/receber.png);\n"
"background-color: qradialgradient(spread:pad,cx:0.5,cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop: 0 rgba(255,255,255,0));")
        self.btn_receber.setText("")
        self.btn_receber.setObjectName("btn_receber")
        self.btn_caixa = QtWidgets.QPushButton(self.centralwidget)
        self.btn_caixa.setGeometry(QtCore.QRect(420, 0, 61, 61))
        self.btn_caixa.setStyleSheet("image: url(:/icon_caixa/icons/caixa.png);\n"
"background-color: qradialgradient(spread:pad,cx:0.5,cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop: 0 rgba(255,255,255,0));")
        self.btn_caixa.setText("")
        self.btn_caixa.setObjectName("btn_caixa")
        self.btn_sair = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sair.setGeometry(QtCore.QRect(480, 0, 61, 61))
        self.btn_sair.setStyleSheet("image: url(:/icon_sair/icons/sair.png);\n"
"background-color: qradialgradient(spread:pad,cx:0.5,cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop: 0 rgba(255,255,255,0));")
        self.btn_sair.setText("")
        self.btn_sair.setObjectName("btn_sair")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 548, 26))
        self.menubar.setObjectName("menubar")
        self.menuCadastros = QtWidgets.QMenu(self.menubar)
        self.menuCadastros.setObjectName("menuCadastros")
        self.menuOpera_es = QtWidgets.QMenu(self.menubar)
        self.menuOpera_es.setObjectName("menuOpera_es")
        self.menuSaida_de_produtos = QtWidgets.QMenu(self.menuOpera_es)
        self.menuSaida_de_produtos.setObjectName("menuSaida_de_produtos")
        self.menuEstoque = QtWidgets.QMenu(self.menuOpera_es)
        self.menuEstoque.setObjectName("menuEstoque")
        self.menuCompras = QtWidgets.QMenu(self.menuOpera_es)
        self.menuCompras.setObjectName("menuCompras")
        self.menuFinanceiro = QtWidgets.QMenu(self.menubar)
        self.menuFinanceiro.setObjectName("menuFinanceiro")
        self.menuConsultas = QtWidgets.QMenu(self.menubar)
        self.menuConsultas.setObjectName("menuConsultas")
        self.menuVendas = QtWidgets.QMenu(self.menuConsultas)
        self.menuVendas.setObjectName("menuVendas")
        self.menuConsumo = QtWidgets.QMenu(self.menuConsultas)
        self.menuConsumo.setObjectName("menuConsumo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCliente = QtWidgets.QAction(MainWindow)
        self.actionCliente.setObjectName("actionCliente")
        self.actionFornecedor = QtWidgets.QAction(MainWindow)
        self.actionFornecedor.setObjectName("actionFornecedor")
        self.actionUsuarios = QtWidgets.QAction(MainWindow)
        self.actionUsuarios.setObjectName("actionUsuarios")
        self.actionVenda = QtWidgets.QAction(MainWindow)
        self.actionVenda.setObjectName("actionVenda")
        self.actionConsumo_de_produtos = QtWidgets.QAction(MainWindow)
        self.actionConsumo_de_produtos.setObjectName("actionConsumo_de_produtos")
        self.actionSaldo = QtWidgets.QAction(MainWindow)
        self.actionSaldo.setObjectName("actionSaldo")
        self.actionCompras_2 = QtWidgets.QAction(MainWindow)
        self.actionCompras_2.setObjectName("actionCompras_2")
        self.actionPedidos = QtWidgets.QAction(MainWindow)
        self.actionPedidos.setObjectName("actionPedidos")
        self.actionCancelar = QtWidgets.QAction(MainWindow)
        self.actionCancelar.setObjectName("actionCancelar")
        self.actionCaixa = QtWidgets.QAction(MainWindow)
        self.actionCaixa.setObjectName("actionCaixa")
        self.actionContas_bancos = QtWidgets.QAction(MainWindow)
        self.actionContas_bancos.setObjectName("actionContas_bancos")
        self.actionContas_a_pagar = QtWidgets.QAction(MainWindow)
        self.actionContas_a_pagar.setObjectName("actionContas_a_pagar")
        self.actionContas_pagas = QtWidgets.QAction(MainWindow)
        self.actionContas_pagas.setObjectName("actionContas_pagas")
        self.actionContas_a_receber = QtWidgets.QAction(MainWindow)
        self.actionContas_a_receber.setObjectName("actionContas_a_receber")
        self.actionContas_recebidas = QtWidgets.QAction(MainWindow)
        self.actionContas_recebidas.setObjectName("actionContas_recebidas")
        self.actionGeral = QtWidgets.QAction(MainWindow)
        self.actionGeral.setObjectName("actionGeral")
        self.actionResumido = QtWidgets.QAction(MainWindow)
        self.actionResumido.setObjectName("actionResumido")
        self.actionGeral_2 = QtWidgets.QAction(MainWindow)
        self.actionGeral_2.setObjectName("actionGeral_2")
        self.actionResumido_2 = QtWidgets.QAction(MainWindow)
        self.actionResumido_2.setObjectName("actionResumido_2")
        self.menuCadastros.addAction(self.actionCliente)
        self.menuCadastros.addSeparator()
        self.menuCadastros.addAction(self.actionFornecedor)
        self.menuCadastros.addSeparator()
        self.menuCadastros.addAction(self.actionUsuarios)
        self.menuSaida_de_produtos.addAction(self.actionVenda)
        self.menuSaida_de_produtos.addSeparator()
        self.menuSaida_de_produtos.addAction(self.actionConsumo_de_produtos)
        self.menuEstoque.addAction(self.actionSaldo)
        self.menuCompras.addAction(self.actionCompras_2)
        self.menuCompras.addSeparator()
        self.menuCompras.addAction(self.actionPedidos)
        self.menuCompras.addSeparator()
        self.menuCompras.addAction(self.actionCancelar)
        self.menuOpera_es.addAction(self.menuEstoque.menuAction())
        self.menuOpera_es.addSeparator()
        self.menuOpera_es.addAction(self.menuCompras.menuAction())
        self.menuOpera_es.addSeparator()
        self.menuOpera_es.addAction(self.menuSaida_de_produtos.menuAction())
        self.menuFinanceiro.addAction(self.actionCaixa)
        self.menuFinanceiro.addSeparator()
        self.menuFinanceiro.addAction(self.actionContas_bancos)
        self.menuFinanceiro.addSeparator()
        self.menuFinanceiro.addAction(self.actionContas_a_pagar)
        self.menuFinanceiro.addSeparator()
        self.menuFinanceiro.addAction(self.actionContas_pagas)
        self.menuFinanceiro.addSeparator()
        self.menuFinanceiro.addAction(self.actionContas_a_receber)
        self.menuFinanceiro.addSeparator()
        self.menuFinanceiro.addAction(self.actionContas_recebidas)
        self.menuVendas.addAction(self.actionGeral)
        self.menuVendas.addSeparator()
        self.menuVendas.addAction(self.actionResumido)
        self.menuConsumo.addAction(self.actionGeral_2)
        self.menuConsumo.addSeparator()
        self.menuConsumo.addAction(self.actionResumido_2)
        self.menuConsultas.addAction(self.menuVendas.menuAction())
        self.menuConsultas.addSeparator()
        self.menuConsultas.addAction(self.menuConsumo.menuAction())
        self.menubar.addAction(self.menuCadastros.menuAction())
        self.menubar.addAction(self.menuOpera_es.menuAction())
        self.menubar.addAction(self.menuFinanceiro.menuAction())
        self.menubar.addAction(self.menuConsultas.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        
     
        
        
              
       
        

    def retranslateUi(self, MainWindow):
            
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lb_logoEmpresa.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.menuCadastros.setTitle(_translate("MainWindow", "Cadastros"))
        self.menuOpera_es.setTitle(_translate("MainWindow", "Operações"))
        self.menuSaida_de_produtos.setTitle(_translate("MainWindow", "Saida de produtos"))
        self.menuEstoque.setTitle(_translate("MainWindow", "Estoque"))
        self.menuCompras.setTitle(_translate("MainWindow", "Compras"))
        self.menuFinanceiro.setTitle(_translate("MainWindow", "Financeiro"))
        self.menuConsultas.setTitle(_translate("MainWindow", "Consultas"))
        self.menuVendas.setTitle(_translate("MainWindow", "Vendas"))
        self.menuConsumo.setTitle(_translate("MainWindow", "Consumo"))
        self.actionCliente.setText(_translate("MainWindow", "Cliente"))
        self.actionFornecedor.setText(_translate("MainWindow", "Fornecedor"))
        self.actionUsuarios.setText(_translate("MainWindow", "Usuarios"))
        self.actionVenda.setText(_translate("MainWindow", "Venda"))
        self.actionConsumo_de_produtos.setText(_translate("MainWindow", "Consumo de produtos"))
        self.actionSaldo.setText(_translate("MainWindow", "Saldo"))
        self.actionCompras_2.setText(_translate("MainWindow", "Compras"))
        self.actionPedidos.setText(_translate("MainWindow", "Pedir"))
        self.actionCancelar.setText(_translate("MainWindow", "Cancelar"))
        self.actionCaixa.setText(_translate("MainWindow", "Caixa"))
        self.actionContas_bancos.setText(_translate("MainWindow", "Contas bancos"))
        self.actionContas_a_pagar.setText(_translate("MainWindow", "Contas a pagar"))
        self.actionContas_pagas.setText(_translate("MainWindow", "Contas pagas"))
        self.actionContas_a_receber.setText(_translate("MainWindow", "Contas a receber"))
        self.actionContas_recebidas.setText(_translate("MainWindow", "Contas recebidas"))
        self.actionGeral.setText(_translate("MainWindow", "Geral"))
        self.actionResumido.setText(_translate("MainWindow", "Resumido"))
        self.actionGeral_2.setText(_translate("MainWindow", "Geral"))
        self.actionResumido_2.setText(_translate("MainWindow", "Resumido"))
     #Funções sistema
        ##Fechar sistema##
           
        #botões sistema
        self.btn_sair.clicked.connect(self.sairSistema)
        self.btn_cliente.clicked.connect(self.telaCliente)
        self.actionCliente.triggered.connect(self.telaCliente) 
        

                    #Funções sistema#
        #sair sistema
    def sairSistema(self):
         print('fechando sistemas')
         sys.exit()
        
        #Abre tela Cliente
    def telaCliente(self):
        self.form_cliente = QtWidgets.QWidget()
        self.ui = Ui_form_cliente()
        self.ui.setupUi(self.form_cliente)
        self.form_cliente.show()    
        print('Abrindo tela cliente')
       
  
        
        
## Imagens Sistema#
import icon_bancos
import icon_caixa
import icon_cliente
import icon_fornecedor
import icon_pagar
import icon_produtos
import icon_receber
import icon_sair
import icon_vendas
import logo_empresa


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
